<?php

namespace GestionClubBundle\Repository;

/**
 * socioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class socioRepository extends \Doctrine\ORM\EntityRepository
{
}
