paciente_index:
    path:     /
    defaults: { _controller: "gestionmedicaBundle:Paciente:index" }
    methods:  GET

paciente_show:
    path:     /{id}/show
    defaults: { _controller: "gestionmedicaBundle:Paciente:show" }
    methods:  GET

paciente_new:
    path:     /new
    defaults: { _controller: "gestionmedicaBundle:Paciente:new" }
    methods:  [GET, POST]

paciente_edit:
    path:     /{id}/edit
    defaults: { _controller: "gestionmedicaBundle:Paciente:edit" }
    methods:  [GET, POST]

paciente_delete:
    path:     /{id}/delete
    defaults: { _controller: "gestionmedicaBundle:Paciente:delete" }
    methods:  DELETE
