clinicaBundle\Entity\DetalleConsulta:
    type: entity
    table: detalle_consulta
    indexes:
        fk_detalle_consulta_consulta:
            columns:
                - consulta_id
        fk_detalle_consulta_tratamiento:
            columns:
                - tratamiento_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cantidad:
            type: integer
            nullable: true
            options:
                unsigned: false
    manyToOne:
        consulta:
            targetEntity: Consulta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                consulta_id:
                    referencedColumnName: id
            orphanRemoval: false
        tratamiento:
            targetEntity: Tratamiento
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tratamiento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
